/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCredibilityRouteImport } from './routes/_authenticated/credibility'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminExportRouteImport } from './routes/_authenticated/admin/export'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated/admin/rules'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as ApiUploadsFilenameRouteImport } from './routes/api/uploads/$filename'
import { Route as AuthenticatedAdminLoansLoanIdRouteImport } from './routes/_authenticated/admin/loans.$loanId'
import { Route as AuthenticatedAdminUserUserIdRouteImport } from './routes/_authenticated/admin/user.$userId'
import { Route as ApiPublicMpesaB2cResultRouteImport } from './routes/api/public/mpesa/b2c-result'
import { Route as ApiPublicMpesaStkCallbackRouteImport } from './routes/api/public/mpesa/stk-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredibilityRoute =
  AuthenticatedCredibilityRouteImport.update({
    id: '/credibility',
    path: '/credibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminExportRoute =
  AuthenticatedAdminExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiUploadsFilenameRoute = ApiUploadsFilenameRouteImport.update({
  id: '/api/uploads/$filename',
  path: '/api/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLoansLoanIdRoute =
  AuthenticatedAdminLoansLoanIdRouteImport.update({
    id: '/loans/$loanId',
    path: '/loans/$loanId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUserUserIdRoute =
  AuthenticatedAdminUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMpesaB2cResultRoute = ApiPublicMpesaB2cResultRouteImport.update({
  id: '/api/public/mpesa/b2c-result',
  path: '/api/public/mpesa/b2c-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaStkCallbackRoute =
  ApiPublicMpesaStkCallbackRouteImport.update({
    id: '/api/public/mpesa/stk-callback',
    path: '/api/public/mpesa/stk-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/credibility': typeof AuthenticatedCredibilityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/loans/$loanId': typeof AuthenticatedAdminLoansLoanIdRoute
  '/admin/user/$userId': typeof AuthenticatedAdminUserUserIdRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/credibility': typeof AuthenticatedCredibilityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/loans/$loanId': typeof AuthenticatedAdminLoansLoanIdRoute
  '/admin/user/$userId': typeof AuthenticatedAdminUserUserIdRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/credibility': typeof AuthenticatedCredibilityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/admin/export': typeof AuthenticatedAdminExportRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/uploads/$filename': typeof ApiUploadsFilenameRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/loans/$loanId': typeof AuthenticatedAdminLoansLoanIdRoute
  '/_authenticated/admin/user/$userId': typeof AuthenticatedAdminUserUserIdRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/account'
    | '/admin'
    | '/credibility'
    | '/dashboard'
    | '/loans'
    | '/notifications'
    | '/referrals'
    | '/staff'
    | '/admin/export'
    | '/admin/products'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/api/uploads/$filename'
    | '/admin/'
    | '/admin/loans/$loanId'
    | '/admin/user/$userId'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/stk-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/account'
    | '/credibility'
    | '/dashboard'
    | '/loans'
    | '/notifications'
    | '/referrals'
    | '/staff'
    | '/admin/export'
    | '/admin/products'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/api/uploads/$filename'
    | '/admin'
    | '/admin/loans/$loanId'
    | '/admin/user/$userId'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/stk-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/credibility'
    | '/_authenticated/dashboard'
    | '/_authenticated/loans'
    | '/_authenticated/notifications'
    | '/_authenticated/referrals'
    | '/_authenticated/staff'
    | '/_authenticated/admin/export'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/rules'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/api/uploads/$filename'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/loans/$loanId'
    | '/_authenticated/admin/user/$userId'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/stk-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  ApiUploadsFilenameRoute: typeof ApiUploadsFilenameRoute
  ApiPublicMpesaB2cResultRoute: typeof ApiPublicMpesaB2cResultRoute
  ApiPublicMpesaStkCallbackRoute: typeof ApiPublicMpesaStkCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credibility': {
      id: '/_authenticated/credibility'
      path: '/credibility'
      fullPath: '/credibility'
      preLoaderRoute: typeof AuthenticatedCredibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/export': {
      id: '/_authenticated/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AuthenticatedAdminExportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rules': {
      id: '/_authenticated/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/uploads/$filename': {
      id: '/api/uploads/$filename'
      path: '/api/uploads/$filename'
      fullPath: '/api/uploads/$filename'
      preLoaderRoute: typeof ApiUploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/loans/$loanId': {
      id: '/_authenticated/admin/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/admin/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedAdminLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/user/$userId': {
      id: '/_authenticated/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUserUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mpesa/b2c-result': {
      id: '/api/public/mpesa/b2c-result'
      path: '/api/public/mpesa/b2c-result'
      fullPath: '/api/public/mpesa/b2c-result'
      preLoaderRoute: typeof ApiPublicMpesaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/stk-callback': {
      id: '/api/public/mpesa/stk-callback'
      path: '/api/public/mpesa/stk-callback'
      fullPath: '/api/public/mpesa/stk-callback'
      preLoaderRoute: typeof ApiPublicMpesaStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminExportRoute: typeof AuthenticatedAdminExportRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLoansLoanIdRoute: typeof AuthenticatedAdminLoansLoanIdRoute
  AuthenticatedAdminUserUserIdRoute: typeof AuthenticatedAdminUserUserIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminExportRoute: AuthenticatedAdminExportRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLoansLoanIdRoute: AuthenticatedAdminLoansLoanIdRoute,
  AuthenticatedAdminUserUserIdRoute: AuthenticatedAdminUserUserIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCredibilityRoute: typeof AuthenticatedCredibilityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCredibilityRoute: AuthenticatedCredibilityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  ApiUploadsFilenameRoute: ApiUploadsFilenameRoute,
  ApiPublicMpesaB2cResultRoute: ApiPublicMpesaB2cResultRoute,
  ApiPublicMpesaStkCallbackRoute: ApiPublicMpesaStkCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
